services:
  - type: web
    name: sih26032-smart-farmer-procurement
    env: python
    buildCommand: "cd frontend && npm install && npx vite build && cd ../backend && pip install -r requirements.txt"
    startCommand: "cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
